### ISSUE TITLE
Initial onboarding DO is referring to an Azure module file that no longer exists

### ISSUE THREAD

**Issue by memes** [f5devcentral/terraform-gcp-bigip-module#6]
Spotted during testing; [startup-script.tpl](../blob/main/startup-script.tpl#L19) is downloading a DO template from Azure module that no longer exists in HEAD. During boot, the startup-script will try to download from https://raw.githubusercontent.com/f5devcentral/terraform-azure-bigip-module/dev_saketha_runtimeinit/config/onboard_do.json which no longer exists.

Suggest that a similar `onboard_do.json` is added to this module too.

**Comment by papineni87** [comment]
Fixed in the latest master branch
